// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: asignado_a.sql

package database

import (
	"context"
	"database/sql"
)

const createProyectoAsignado = `-- name: CreateProyectoAsignado :one
INSERT INTO asignado_a (cientifico,proyecto,dedicacion)
VALUES ($1, $2, $3)
RETURNING cientifico, proyecto, dedicacion
`

type CreateProyectoAsignadoParams struct {
	Cientifico string
	Proyecto   string
	Dedicacion sql.NullInt32
}

func (q *Queries) CreateProyectoAsignado(ctx context.Context, arg CreateProyectoAsignadoParams) (AsignadoA, error) {
	row := q.db.QueryRowContext(ctx, createProyectoAsignado, arg.Cientifico, arg.Proyecto, arg.Dedicacion)
	var i AsignadoA
	err := row.Scan(&i.Cientifico, &i.Proyecto, &i.Dedicacion)
	return i, err
}
