// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type AsignadoA struct {
	Cientifico string
	Proyecto   string
	Dedicacion sql.NullInt32
}

type Cientifico struct {
	Dni      string
	Nomapels string
}

type Proyecto struct {
	ID     string
	Nombre string
	Horas  int32
}
