// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: projects.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO proyectos (id,nombre,horas)
VALUES ($1, $2, $3)
RETURNING id, nombre, horas
`

type CreateProjectParams struct {
	ID     string
	Nombre string
	Horas  int32
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Proyecto, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.Nombre, arg.Horas)
	var i Proyecto
	err := row.Scan(&i.ID, &i.Nombre, &i.Horas)
	return i, err
}
