// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: scientists.sql

package database

import (
	"context"
)

const createScientist = `-- name: CreateScientist :one
INSERT INTO cientificos (dni,nomApels)
VALUES ($1, $2)
RETURNING dni, nomapels
`

type CreateScientistParams struct {
	Dni      string
	Nomapels string
}

func (q *Queries) CreateScientist(ctx context.Context, arg CreateScientistParams) (Cientifico, error) {
	row := q.db.QueryRowContext(ctx, createScientist, arg.Dni, arg.Nomapels)
	var i Cientifico
	err := row.Scan(&i.Dni, &i.Nomapels)
	return i, err
}
